# Обработка временного ряда

In [2]:
import pandas as pd

In [42]:
data = pd.read_csv("weather.csv", sep=";", index_col=False)
data.head()

,Местное время в Санкт-Петербурге,T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Cm,Ch,VV,Td,RRR,tR,E,Tg,E',sss
0,24.12.2022 21:00,-1.4,758.3,758.7,1.4,78.0,"Ветер, дующий с западо-северо-запада",2.0,NaN,10.0,...,"Высококучевых, высокослоистых или слоисто-дожд...","Перистых, перисто-кучевых или перисто-слоистых...",10.0,-4.8,Осадков нет,12.0,NaN,NaN,NaN,NaN
1,24.12.2022 18:00,-0.8,756.9,757.3,2.2,79.0,"Ветер, дующий с западо-северо-запада",4.0,NaN,10.0,...,NaN,NaN,10.0,-4.0,Следы осадков,12.0,NaN,NaN,NaN,NaN
2,24.12.2022 15:00,-0.6,754.7,755.1,1.7,79.0,"Ветер, дующий с западо-северо-запада",4.0,NaN,10.0,...,NaN,NaN,10.0,-3.9,NaN,NaN,NaN,NaN,NaN,NaN
3,24.12.2022 12:00,-1.7,753.0,753.4,2.3,83.0,"Ветер, дующий с северо-запада",3.0,NaN,10.0,...,"Высококучевых, высокослоистых или слоисто-дожд...","Перистых, перисто-кучевых или перисто-слоистых...",10.0,-4.2,NaN,NaN,NaN,NaN,NaN,NaN
4,24.12.2022 09:00,-1.3,750.7,751.0,3.2,84.0,"Ветер, дующий с запада",2.0,NaN,NaN,...,NaN,NaN,10.0,-3.7,0.9,12.0,NaN,NaN,Ровный слой сухого рассыпчатого снега покрывае...,8.0

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14602 entries, 0 to 14601
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Местное время в Санкт-Петербурге  14602 non-null  object
 1   T                                 14599 non-null  float64
 2   Po                                14599 non-null  float64
 3   P                                 14599 non-null  float64
 4   Pa                                14576 non-null  float64
 5   U                                 14594 non-null  float64
 6   DD                                14594 non-null  object
 7   Ff                                14598 non-null  float64
 8   ff10                              258 non-null    float64
 9   ff3                               1177 non-null   float64
 10  N                                 14567 non-null  object
 11  WW                                14602 non-null  object
 12  W1                                5026 non-null   object
 13  W2                                5025 non-null   object
 14  Tn                                3644 non-null   float64
 15  Tx                                1821 non-null   float64
 16  Cl                                12349 non-null  object
 17  Nh                                12348 non-null  object
 18  H                                 12392 non-null  object
 19  Cm                                8382 non-null   object
 20  Ch                                6330 non-null   object
 21  VV                                14595 non-null  float64
 22  Td                                14597 non-null  float64
 23  RRR                               7248 non-null   object
 24  tR                                7248 non-null   float64
 25  E                                 800 non-null    object
 26  Tg                                800 non-null    float64
 27  E'                                547 non-null    object
 28  sss                               545 non-null    object
dtypes: float64(14), object(15)
memory usage: 3.2+ MB

In [44]:
data["Date"] = pd.to_datetime(data["Местное время в Санкт-Петербурге"].copy(deep=True)).dt.date

In [45]:
data = data.drop("Местное время в Санкт-Петербурге", axis=1)

In [46]:
data_temperature = data[["Date", "T"]].copy(deep=True)

In [47]:
data_temperature.head()

         Date    T
0  2022-12-24 -1.4
1  2022-12-24 -0.8
2  2022-12-24 -0.6
3  2022-12-24 -1.7
4  2022-12-24 -1.3

In [48]:
data_temperature_grouped = data_temperature.groupby(by="Date", as_index=False).mean()

In [49]:
data_temperature_grouped.to_csv("weather_grouped.csv", index=False)